### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by ctmbl** [eskerda/cmdbikes#12]
Hi @eskerda 👋 
Tks a lot for your series of project around bike sharing: pybikes, citybikes and cmdbikes, really love what you created ❤ 

just a suggestion, you have a wrongly formatted link in the README 😉 

![Image](https://github.com/user-attachments/assets/8d13ab72-b25a-4078-90cc-9ce3f6481e55)

sorry I didn't create a PR for that, I personally don't like to be added to "contributors" by GitHub for spotting one typo in a readme ahah

**Comment by eskerda** [comment]
Thanks for reporting! glad you like the project.

Fixed in https://github.com/eskerda/cmdbikes/commit/cfbe20a6f93a45bd0698683a9bb50252d2a7c52f

**Comment by ctmbl** [comment]
@eskerda sorry for insisting but the URL is still wrong after [cfbe20a](https://github.com/eskerda/cmdbikes/commit/cfbe20a6f93a45bd0698683a9bb50252d2a7c52f) 😅 
I think it should be:
```diff
-.. _`pybikes`: https//github.com/eskerda/pybikes
+.. _`pybikes`: https://github.com/eskerda/pybikes
```

**Comment by eskerda** [comment]
My bad ;) https://github.com/eskerda/cmdbikes/commit/9bc42996934ab7e686fc419a898e91e0a1ed563f
